CREATE TABLE [dbo].[RSSFeeds]
(
[RSSFeedID] [int] NOT NULL IDENTITY(1, 1),
[FeedName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Checked] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[RSSFeeds] ADD CONSTRAINT [PK__RSSFeeds__DF1690F2DC8BA093] PRIMARY KEY CLUSTERED  ([RSSFeedID]) ON [PRIMARY]
GO
